# Generated by Django 6.0.7 on 2026-07-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchaseinvoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
