# Generated by Django 6.0.7 on 2026-07-26 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
